all:
	mkdir -p obj
	g++ -o obj/main main.cpp sort.cpp -Wall -O2 -g -lpthread -mavx -mavx2 -mfma

clean:
	rm -rf obj

original:
	g++ -o obj/main main.cpp sort.cpp -Wall -O2 -g -lpthread -mavx -mavx2 -mfma
